=== Saphyr55/U3T/u3t-sample-ioc/src/main/resources/module.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  
  <xs:attributeGroup name="component-attributes">
    <xs:attribute name="id" type="xs:string" />
    <xs:attribute name="class" type="xs:string" />
  </xs:attributeGroup>

  <xs:complexType name="arg-type">
    <xs:attribute name="name" type="xs:string" />
    <xs:attribute name="type" type="xs:string" />
    <xs:attribute name="value" type="xs:string" />
  </xs:complexType>

  <xs:complexType name="constructor-args-type">
    <xs:sequence>
      <xs:element name="arg" minOccurs="0" maxOccurs="unbounded" type="arg-type" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="component-type">
    <xs:sequence>
      <xs:element type="constructor-args-type" minOccurs="0" maxOccurs="unbounded" name="constructor-args"/>
    </xs:sequence>
    <xs:attributeGroup ref="component-attributes"/>
  </xs:complexType>

  <xs:complexType name="ref-component-type">
    <xs:attribute name="ref" type="xs:string" />
  </xs:complexType>

  <xs:complexType name="add-component-type">
    <xs:sequence>
      <xs:element name="component" type="component-type" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="ref-component" type="ref-component-type" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="class" type="xs:string"/>
  </xs:complexType>

  <xs:complexType name="module-type">
    <xs:sequence>
      <xs:element name="name" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="component" type="component-type" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="add-component" type="add-component-type" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:element name="module" type="module-type"/>

</xs:schema>

=== Saphyr55/U3T/u3t-sample-ioc/src/main/resources/module.xml
<?xml version="1.0" encoding="UTF-8" ?>
<module xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="module.xsd" >

    <component id="Sample.AComponent"
               class="utours.ultimate.ioc.AComponent"
               strategy="derived"
               type="additional" />

    <component class="utours.ultimate.ioc.BComponent"
               id="Sample.BComponent"
               type="additional"
               strategy="derived">

        <constructor-args>

            <arg name="wrapped"
                 value="Sample.AComponent"
                 type="utours.ultimate.ui.ComponentInterface" />

        </constructor-args>

    </component>

    <add-component class="utours.ultimate.ui.ComponentInterface">

        <component id="Sample.CComponent"
                   class="utours.ultimate.ioc.CComponent"
                   strategy="derived"
                   type="additional" />

        <ref-component ref="Sample.AComponent" />

    </add-component>

</module>
